services:
  backend:
    # image: ffalanges/aws-docker-node:latest
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    command: npm run start:dev
    ports:
      - "3000:3000"
networks:
  node-network:
    driver: bridge
